### ISSUE TITLE
爬了3000多个subject  后面就不行了，是怎么回事啊，代码没看懂

### ISSUE THREAD

**Issue by lxl315** [40robber/ScrapyDouban#10]
如题是因为页面上已经匹配到的url 都爬过的原因么？

**Comment by 40robber** [comment]
@lxl315 如果不是 IP 被 ban，可以在[这里](https://github.com/40robber/ScrapyDouban/blob/bf3a1e4bfcdbbf64572756708176ed96e16f8b87/scrapy/douban/spiders/movie_subject.py#L16)添加一些初始的 url，原理就是无法枚举豆瓣 subject_id，可以通过它的推荐来获取尽可能多的 subject_id

**Comment by lxl315** [comment]
嗯，这个我看到了。试过。
另外我想改造下您的项目从一个ip接口，获取代理ip，然后爬取信息，如果ip被ban 了，就从接口里在获取一个ip，如果没有被ban，就一直用这个代理ip爬

**Comment by 40robber** [comment]
@lxl315 既然你有 IP 接口那么随机取一个IP出来应该更好，长时间用一个 IP 很容易被让 IP ban掉，如果你维护一个可用的 IP 列表，随机取一个，放慢抓取的频率，这样才不容易被 ban

**Comment by lxl315** [comment]
好的。我去继续优化
