### ISSUE TITLE
小白问一句

### ISSUE THREAD

**Issue by xiaoguiwk** [40robber/ScrapyDouban#12]
没有用过docker，所以多嘴问一句，在Linux命令行下应该如何管理数据库？感谢。

**Comment by 40robber** [comment]
@xiaoguiwk 还是先用图形工具管理吧，项目里面有个 douban_adminer 可以直接管理，可以看一下演示视频里面的操作

**Comment by wweggplant** [comment]
@baabaaox  问一下，爬完豆瓣的书最后有多少数据量呀？
