### ISSUE TITLE
torndb连接数据库有问题？

### ISSUE THREAD

**Issue by LiMin1992** [40robber/ScrapyDouban#2]
作者您好，我想跟着你的代码学习一下爬虫，但是torndb运行不了，我用的python3，出现下面的问题，

CONVERSIONS[field_type] = [(FLAG.BINARY, str)] + CONVERSIONS[field_type]
TypeError: can only concatenate list (not "function") to list

我改了这个 CONVERSIONS[field_type] = [(FLAG.BINARY, str)] +[   CONVERSIONS[field_type]   ]，就是给+号后面加了的变量加了[],但是数据库还是连不上
求大神帮帮忙，谢谢了

**Comment by 40robber** [comment]
已经升级到 Python3 切换到 PyMySQL

**Comment by 40robber** [comment]
@LiMin1992 已经升级到 Python3 切换到 PyMySQL
