### ISSUE TITLE
太难装了有木有

### ISSUE THREAD

**Issue by Nicolana** [40robber/ScrapyDouban#8]
太难装了有木有

**Comment by 40robber** [comment]
@Nicolana 在哪一步碰到问题？

**Comment by Nicolana** [comment]
一开始是docker连网的问题，后来是pip安装依赖的问题。

**Comment by Nicolana** [comment]
> @Nicolana 在哪一步碰到问题？

一开始是docker连网的问题，后来是pip安装依赖的问题。

**Comment by lxl315** [comment]
creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitonlgxats.c -o tmp/xmlXPathInitonlgxats.o
    /tmp/xmlXPathInitonlgxats.c:2:1: warning: return type defaults to 'int' [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    cc tmp/xmlXPathInitonlgxats.o -L/usr/lib -lxml2 -o a.out
    error: command 'gcc' failed with exit status 4
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c78el0ad/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-w74phaqz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-c78el0ad/lxml/

ERROR: Service 'scrapy' failed to build: The command '/bin/sh -c apk add --update --no-cache gcc musl-dev libffi-dev libxml2-dev libxslt-dev jpeg-dev curl-dev make python3 python3-dev tzdata git curl && cp /usr/share/zoneinfo/Asia/Chongqing /etc/localtime && echo 'Asia/Chongqing' > /etc/timezone && apk del tzdata && python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ --upgrade pip && python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ scrapy pymysql pillow arrow scylla && git clone https://github.com/40robber/ScrapyDouban.git /srv/ScrapyDouban' returned a non-zero code: 1

docker 配置到这里报错了

**Comment by lxl315** [comment]
好像是容器安装lxml 报错了？

**Comment by RabpitOO** [comment]
问一下这个配置的流程呢？
